src/Entity/Log.php
<?php

namespace App\Entity;

use App\Entity\Trait\IdFieldTrait;
use App\Repository\LogRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LogRepository::class)]
class Log
{
    use IdFieldTrait;

    public const ICON = 'activity';

    public const LEVELS = [
        100 => 'DEBUG',
        200 => 'INFO',
        250 => 'NOTICE',
        300 => 'WARNING',
        400 => 'ERROR',
        500 => 'CRITICAL',
        550 => 'ALERT',
        600 => 'EMERGENCY',
    ];

    #[ORM\Column(type: Types::TEXT)]
    private ?string $message = null;

    #[ORM\Column(type: Types::DATETIME_IMMUTABLE)]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(type: Types::INTEGER)]
    private ?int $level = null;

    #[ORM\Column(type: Types::STRING, length: 10)]
    private ?string $levelName = null;

    #[ORM\Column(type: Types::STRING, length: 20)]
    private ?string $channel = null;

    #[ORM\Column(type: Types::JSON)]
    private array $context = [];

    #[ORM\Column(type: Types::JSON)]
    private array $extra = [];

    #[ORM\ManyToOne(inversedBy: 'logs')]
    private ?User $user = null;

    public function __toString(): string 
    {
        return sprintf('#%d', $this->id);
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): static
    {
        $this->message = $message;
        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;
        return $this;
    }

    public function getLevel(): ?int
    {
        return $this->level;
    }

    public function setLevel(int $level): static
    {
        $this->level = $level;
        return $this;
    }

    public function getLevelName(): ?string
    {
        return $this->levelName;
    }

    public function setLevelName(string $levelName): static
    {
        $this->levelName = $levelName;
        return $this;
    }

    public function getChannel(): ?string
    {
        return $this->channel;
    }

    public function setChannel(string $channel): static
    {
        $this->channel = $channel;
        return $this;
    }

    public function getContext(): array
    {
        return $this->context;
    }

    public function setContext(array $context): static
    {
        $this->context = $context;
        return $this;
    }

    public function getExtra(): array
    {
        return $this->extra;
    }

    public function setExtra(array $extra): static
    {
        $this->extra = $extra;
        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;
        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Entity\Trait\{DateFieldTrait, IdFieldTrait};
use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\{PasswordAuthenticatedUserInterface, UserInterface};

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_PSEUDO', fields: ['pseudo'])]
#[UniqueEntity(fields: ['pseudo'], message: 'There is already an account with this pseudo')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    use IdFieldTrait, DateFieldTrait;

    public const ICON = 'user';
    public const ICONS = 'users';

    public const ROLES = [
        'Administrateur' => 'ROLE_ADMIN',
        'Application' => 'ROLE_APP',
        'Inactif' => 'ROLE_CLOSE',
    ];

    #[ORM\Column(type: Types::STRING, length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column(type: Types::STRING)]
    private ?string $password = null;

    #[ORM\Column(type: Types::STRING, length: 20)]
    private ?string $pseudo = null;

    #[ORM\Column(type: Types::STRING, length: 50, nullable: true)]
    private ?string $firstname = null;

    #[ORM\Column(type: Types::STRING, length: 50, nullable: true)]
    private ?string $lastname = null;

    #[ORM\Column(type: Types::STRING, length: 20, nullable: true)]
    private ?string $phone = null;

    #[ORM\Column(type: Types::STRING, length: 7)]
    private string $color = '#000000';

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column]
    private bool $isVerified = false;

    /**
     * @var Collection<int, Token>
     */
    #[ORM\OneToMany(targetEntity: Token::class, mappedBy: 'user', orphanRemoval: true, cascade: ['persist'])]
    private Collection $tokens;

    /**
     * @var Collection<int, Log>
     */
    #[ORM\OneToMany(targetEntity: Log::class, mappedBy: 'user')]
    private Collection $logs;

    public function __construct()
    {
        $this->tokens = new ArrayCollection();
        $this->logs = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->getUserIdentifier();
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;
        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->pseudo;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        $roles[] = 'ROLE_USER';
        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;
        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;
        return $this;
    }

    /** @codeCoverageIgnore */
    #[\Deprecated]
    public function eraseCredentials(): void
    {
        // @deprecated, to be removed when upgrading to Symfony 8
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): static
    {
        $this->pseudo = $pseudo;
        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(?string $firstname): static
    {
        $this->firstname = $firstname;
        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): static
    {
        $this->lastname = $lastname;
        return $this;
    }

    public function getFullname(): string
    {
        return sprintf('%s %s', $this->firstname, $this->lastname);
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): static
    {
        $this->phone = $phone;
        return $this;
    }

    public function getColor(): string
    {
        return $this->color;
    }

    public function setColor(?string $color): static
    {
        $this->color = $color;
        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;
        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;
        return $this;
    }

    /**
     * @return Collection<int, Token>
     */
    public function getTokens(): Collection
    {
        return $this->tokens;
    }

    /**
     * @codeCoverageIgnore
     */
    public function addToken(Token $token): static
    {
        if (!$this->tokens->contains($token)) {
            $this->tokens->add($token);
            $token->setUser($this);
        }
        return $this;
    }

    /**
     * @codeCoverageIgnore
     */
    public function removeToken(Token $token): static
    {
        if ($this->tokens->removeElement($token)) {
            if ($token->getUser() === $this) {
                $token->setUser(null);
            }
        }
        return $this;
    }

    /**
     * @return Collection<int, Log>
     */
    public function getLogs(): Collection
    {
        return $this->logs;
    }

    /**
     * @codeCoverageIgnore
     */
    public function addLog(Log $log): static
    {
        if (!$this->logs->contains($log)) {
            $this->logs->add($log);
            $log->setUser($this);
        }
        return $this;
    }

    /**
     * @codeCoverageIgnore
     */
    public function removeLog(Log $log): static
    {
        if ($this->logs->removeElement($log)) {
            if ($log->getUser() === $this) {
                $log->setUser(null);
            }
        }
        return $this;
    }
}

src/Controller/LogController.php
<?php

namespace App\Controller;

use App\Entity\Log;
use App\Form\LogSearchForm;
use App\Model\LogSearchModel;
use App\Repository\LogRepository;
use App\Service\ChartJsService;
use Symfony\Component\HttpFoundation\{Request, Response};
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Routing\Requirement\Requirement;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/log', name: 'log.')]
#[IsGranted('ROLE_APP')]
final class LogController extends AppAbstractController
{
    #[Route('/list', name: 'list', methods: ['GET'])]
    public function list(LogRepository $logRepository, Request $request): Response
    {
        $search = new LogSearchModel();
        $form = $this->createForm(LogSearchForm::class, $search);
        $form->handleRequest($request);

        $title = 'Liste logs';
        $this->addLog($title, [
            'action' => __FUNCTION__,
            'entity' => 'Log',
        ]);
        return $this->render('log/list.html.twig', [
            'title' => $title,
            'logs' => $this->paginate($logRepository->findListQb($search), $request),
            'search' => $form,
        ]);
    }

    #[Route('/show/{id}', name: 'show', methods: ['GET'], requirements: ['id' => Requirement::DIGITS])]
    public function show(Log $log): Response
    {
        $title = 'Voir log';
        $this->addLog($title, [
            'action' => __FUNCTION__,
            'entity' => 'Log',
            'entity_id' => $log->getId(),
        ]);
        return $this->render('log/show.html.twig', [
            'title' => $title,
            'log' => $log,
        ]);
    }

    #[Route('/calendar', name: 'calendar', methods: ['GET'])]
    public function calendar(): Response
    {
        $title = 'Calendrier logs';
        $this->addLog($title, [
            'action' => __FUNCTION__,
            'entity' => 'Log',
        ]);
        return $this->render('log/calendar.html.twig', [
            'title' => $title,
        ]);
    }

    #[Route('/pivottable', name: 'pivottable', methods: ['GET'])]
    public function pivottable(LogRepository $logRepository, Request $request): Response
    {
        if (!$request->isXmlHttpRequest()) {
            return $this->redirectToRoute('log.list', [], Response::HTTP_SEE_OTHER);
        }
        $this->addLog(ucfirst(__FUNCTION__), [
            'action' => __FUNCTION__,
            'entity' => 'Log'
        ]);
        $data = [
            'rows' => ['Annee', 'Mois'],
            'cols' => ['Jour'],
            'aggregate' => ['cnt'],
            'items' => $logRepository->countByAllTime(),
        ];
        return $this->json($data);
    }

    #[Route('/chart', name: 'chart', methods: ['GET'])]
    public function chart(
        LogRepository $logRepository,
        ChartJsService $chartJsService
    ): Response {
        $countHours = $logRepository->countByHour();
        $chartHours = $chartJsService
            ->make('line', ['height' => 70])
            ->setData([
                'labels' => array_column($countHours, 'hour'),
                'datasets' => [
                    [
                        'label' => 'Heures de fréquentation',
                        'borderColor' => '#0dcaf0',
                        'backgroundColor' => '#1abc9c',
                        'tension' => .3,
                        'data' => array_column($countHours, 'cnt')
                    ]
                ]
            ]);

        $countHours = $logRepository->countByDays();
        $chartDays = $chartJsService
            ->make('bar', ['height' => 70])
            ->setData([
                'labels' => array_column($countHours, 'day'),
                'datasets' => [
                    [
                        'label' => 'Jours de fréquentation',
                        'borderColor' => '#0dcaf0',
                        'backgroundColor' => '#1abc9c',
                        'tension' => .3,
                        'data' => array_column($countHours, 'cnt')
                    ]
                ]
            ]);
        $title = 'Graphiques logs';
        $this->addLog($title, [
            'action' => __FUNCTION__,
            'entity' => 'Log'
        ]);
        return $this->render('log/chart.html.twig', [
            'title' => $title,
            'chart_hours' => $chartHours,
            'chart_days' => $chartDays,
        ]);
    }
}

templates/log/_sidebar.html.twig
<ul class="list-group list-group-flush">
	<a href="{{ path('log.list') }}" class="list-group-item list-group-item-action {{ app.current_route == 'log.list' ? 'active' : null }}">
		{{ ux_icon('list') }}
		{{ 'list'|trans|capitalize }}
	</a>
	<a href="{{ path('log.calendar') }}" class="list-group-item list-group-item-action {{ app.current_route == 'log.calendar' ? 'active' : null }}">
		{{ ux_icon('event') }}
		Calendrier fréquentation
	</a>
	<a href="{{ path('log.chart') }}" class="list-group-item list-group-item-action {{ app.current_route == 'log.chart' ? 'active' : null }}">
		{{ ux_icon('chart-line') }}
		Graphiques fréquentation
	</a>
</ul>

templates/log/calendar.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{ title|capitalize }}
	-
	{{ parent() }}
{% endblock %}

{% block body %}

	<div class="d-flex flex-wrap justify-content-between align-items-center border-bottom pt-2 pb-2 mb-3">
		<h1 class="text-white">
			{{ ux_icon(constant('App\\Entity\\Log::ICON'), {class: 'mb-2', width: '35', height: '35'}) }}
			{{ title|capitalize }}
		</h1>
	</div>

	<div class="row">
		<div class="col-md-2">
			{% include "log/_sidebar.html.twig" %}
		</div>
		<div class="col-md-10">
			<div class="card bg-light shadow">
				<div class="card-header">
					<h3 class="h4 card-title">
						{{ ux_icon('bi:calendar4-week', {class: 'mb-2', width: '25', height: '25'}) }}
						Calendrier de fréquentation
					</h3>
				</div>
				<div class="card-body">
					<div id="pvt-log-dates" data-controller="pivottable" data-path="{{ path('log.pivottable') }}"></div>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

templates/log/chart.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{ title }}
	-
	{{ parent() }}
{% endblock %}

{% block body %}
	<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
		<h1 class="text-white">
			{{ ux_icon('chart-line', {class: 'mb-2', width: '30', height: '30'})}}
			{{ title }}
		</h1>
		<div class="btn-toolbar" role="toolbar">
			<a href="{{ path('log.list') }}" class="btn btn-light" title="{{ 'list'|trans|capitalize }}" data-toggle="tooltip">
				{{ ux_icon('list') }}
			</a>
		</div>
	</div>

	<div class="row">
		<div class="col-md-2">
			{% include "log/_sidebar.html.twig" %}
		</div>
		<div class="col-md-10">
			<div class="card bg-light shadow">
				<div class="card-body">{{ render_chart(chart_hours) }}</div>
			</div>
			<div class="card bg-light shadow mt-3">
				<div class="card-body">{{ render_chart(chart_days) }}</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/log/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{ title|capitalize }}
	-
	{{ parent() }}
{% endblock %}

{% block body %}

	<div class="d-flex flex-wrap justify-content-between align-items-center border-bottom pt-2 pb-2 mb-3">
		<h1 class="text-white">
			{{ ux_icon(constant('App\\Entity\\Log::ICON'), {class: 'mb-2', width: '35', height: '35'}) }}
			{{ title|capitalize }}
		</h1>
		<div class="btn-toolbar" role="toolbar">
			<div class="btn-group" role="group">
				<button class="btn btn-light" type="button" data-bs-toggle="offcanvas" data-bs-target="#searchOffCanvas" aria-controls="searchOffCanvas" title="{{ 'filter'|trans|capitalize }}" data-toggle="tooltip">
					{{ search.vars.submitted ? ux_icon('filter-f', {class: 'text-warning mb-1'}) : ux_icon('filter') }}
				</button>
				{% if search.vars.submitted %}
					<a href="{{ path(app.current_route) }}" class="btn btn-light" title="{{ 'delete filters'|trans|capitalize }}" data-toggle="tooltip">
						{{ ux_icon('close', {class: 'text-danger mb-1'}) }}
					</a>
				{% endif %}
			</div>
		</div>
	</div>

	<div class="offcanvas offcanvas-end" tabindex="-1" id="searchOffCanvas" aria-labelledby="searchOffCanvasLabel">
		<div class="offcanvas-header">
			<h5 class="offcanvas-title" id="searchOffCanvasLabel">
				{{ ux_icon('search', {class: 'text-info mb-1'}) }}
				{{ 'search'|trans|capitalize }}
			</h5>
			<button type="button" class="btn-close" data-bs-dismiss="offcanvas"></button>
		</div>
		<div class="offcanvas-body">
			{{ form_start(search) }}
			{{ form_rest(search) }}
			<button class="btn btn-primary w-100" type="submit">
				{{ ux_icon('filter') }}
				{{ 'filter'|trans|capitalize }}
			</button>
			{{ form_end(search) }}
		</div>
	</div>

	<div class="row">
		<div class="col-md-2">
			{% include "log/_sidebar.html.twig" %}
		</div>
		<div class="col-md-10">
			<div class="card bg-light shadow">
				<div class="card-body">
					<table class="table table-sm table-striped table-hover align-middle">
						<thead>
							<tr>
								<th class="text-center">{{ ux_icon('pointer') }}</th>
								<th class="text-center">{{ ux_icon('event')}}</th>
								<th class="text-center">{{ 'message'|trans|capitalize }}</th>
								<th class="text-center">{{ ux_icon(constant('App\\Entity\\User::ICON')) }}</th>
								<th class="text-center">{{ 'level'|trans|capitalize }}</th>
								<th class="text-center">{{ 'channel'|trans|capitalize }}</th>
							</tr>
						</thead>
						<tbody>
							{% for log in logs %}
								<tr>
									<td class="text-center">
										<a href="{{ path('log.show', {id: log.id}) }}" class="btn btn-sm">
											{{ ux_icon('eye', {class: 'text-info'}) }}
										</a>
									</td>
									<td class="text-center">{{ log.createdAt|format_datetime('full', 'short') }}</td>
									<td class="text-center">{{ log.message }}</td>
									<td class="text-center">{{ log.user }}</td>
									<td class="text-center">
										{% include "partials/badge_log.html.twig" with {level: log.level} only %}
									</td>
									<td class="text-center">{{ log.channel }}</td>
								</tr>
							{% endfor %}
						</tbody>
					</table>
					{{ knp_pagination_render(logs) }}
				</div>
			</div>
		</div>
	</div>

{% endblock %}

templates/log/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{ title|capitalize }}
	-
	{{ parent() }}
{% endblock %}

{% block body %}
	
    {% include "partials/page_title.html.twig" with {
        title: title, 
        icon: constant('App\\Entity\\Log::ICON'),
		prefix: 'log'
    } %}

    <table class="table align-middle">
        <tbody>
            <tr>
                <th>{{ 'message'|trans|capitalize }}</th>
                <td>{{ log.message }}</td>
            </tr>
            {% if log.user %}
            <tr>
                <th>{{ ux_icon(constant('App\\Entity\\User::ICON')) }}</th>
                <td>{{ log.user.fullname }}</td>
            </tr>
            {% endif %}
            <tr>
                <th>{{ ux_icon('event') }}</th>
                <td>{{ log.createdAt|format_datetime('full', 'short') }}</td>
            </tr>
            <tr>
                <th>{{ 'level'|trans|capitalize }}</th>
                <td>{% include "partials/badge_log.html.twig" with {level: log.level} only %}</td>
            </tr>
            <tr>
                <th>{{ 'channel'|trans|capitalize }}</th>
                <td>{{ log.channel }}</td>
            </tr>
            <tr>
                <th>{{ 'context'|trans|capitalize }}</th>
                <td>{{ log.context ? log.context|json_encode(constant('JSON_PRETTY_PRINT') b-or constant('JSON_UNESCAPED_SLASHES'))|highlight('json') : '' }}</td>
            </tr>
            <tr>
                <th>{{ 'extra'|trans|capitalize }}</th>
                <td>{{ log.extra ? log.extra|json_encode(constant('JSON_PRETTY_PRINT') b-or constant('JSON_UNESCAPED_SLASHES'))|highlight('json') : '' }}</td>
            </tr>
            <tr>
                <th>Id</th>
                <td>{{ log.id }}</td>
            </tr>
        </tbody>
    </table>
{% endblock %}